/* empty css                      */import{S as c}from"./assets/vendor-C8mLK4Kr.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",function(){let r=null;function n(){const o=window.innerWidth;o>=1439&&!r?r=new c(".reviews-swiper",{slidesPerView:3,spaceBetween:24,loop:!0,slideClass:"reviews-swiper-slide",wrapperClass:"reviews-swiper-wrapper",direction:"horizontal"}):o<1439&&r&&(r.destroy(!0,!0),r=null)}n(),window.addEventListener("resize",n),new c(".gallery-swiper",{breakpoints:{374:{slidesPerView:1.5,spaceBetween:10},1439:{slidesPerView:3.3,spaceBetween:24}},loop:!0,slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",direction:"horizontal"})});document.querySelectorAll(".faq-acc-el-trigger").forEach(r=>{r.addEventListener("click",()=>{const n=r.closest(".faq-acc-el"),o=n.querySelector(".faq-acc-el-descr-frame");n.classList.contains("open")?(n.classList.remove("open"),o.style.maxHeight="0"):(n.classList.add("open"),o.style.maxHeight=o.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),n=r.querySelector(".icon"),o=document.querySelector(".modal"),s=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const i=`
<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 30V26.6667H35V30H5ZM5 21.6667V18.3333H35V21.6667H5ZM5 13.3333V10H35V13.3333H5Z" fill="white" />
</svg>
    `,d=`
<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M10.6663 31.6666L8.33301 29.3333L17.6663 20L8.33301 10.6666L10.6663 8.33331L19.9997 17.6666L29.333 8.33331L31.6663 10.6666L22.333 20L31.6663 29.3333L29.333 31.6666L19.9997 22.3333L10.6663 31.6666Z" fill="white" />
</svg>
    `;r.addEventListener("click",()=>{t=!t,n.innerHTML=t?d:i,t?a():l()}),s.forEach(f=>f.addEventListener("click",()=>{l(),n.innerHTML=i,t=!1})),window.addEventListener("scroll",u);function a(){o.style.display="block"}function l(){o.style.display="none"}function u(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const s=document.getElementById("site-header");return s?s.offsetHeight:0}function n(s){const e=document.getElementById(s);if(!e)return;const t=r(),i=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll('a[href^="#"]').forEach(s=>{s.addEventListener("click",function(e){const t=this.getAttribute("href");if(t.startsWith("index.html#")||t.startsWith("http"))return;e.preventDefault();const i=t.substring(1);n(i)})});const o=window.location.hash;if(o){const s=o.substring(1);setTimeout(()=>{n(s)},1e3)}});
//# sourceMappingURL=index.js.map
